--- 
abstract: Auto-create Business::ISBN objects from columns.
author: K. J. Cheetham C<< <jamie @ shadowcatsystems.co.uk> >>
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: DBIx-Class-InflateColumn-ISBN
no_index: 
  directory: 
    - inc
    - t
requires: 
  Business::ISBN: 1.82
  DBIx::Class: 0.07005
  perl: 5.6.1
tests: t/*.t
version: 0.04000
